package View;

import Model.Produtos;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author paulo.bezerra
 */
public class NovoProdutoTela extends javax.swing.JFrame {

    private int contador = 1;

    /**
     * Creates new form ControleEstoque
     */
    public NovoProdutoTela() {
        initComponents();
        jSpinnerQuantidadeProd.setValue(1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerQuantidadeProd = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        JCodigoBarras = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JPrecoVenda = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        JPrecoCompra = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 340, 130, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Controle de Estoque");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(265, 11, 212, 45);
        getContentPane().add(JNomeProduto);
        JNomeProduto.setBounds(30, 170, 260, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText(" Nome do Produto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 140, 121, 23);
        getContentPane().add(JDescricao);
        JDescricao.setBounds(320, 170, 390, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Descricao");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 140, 160, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Preco Venda");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 220, 110, 20);
        getContentPane().add(jSpinnerQuantidadeProd);
        jSpinnerQuantidadeProd.setBounds(400, 250, 80, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Quantidade");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 220, 90, 20);
        getContentPane().add(JCodigoBarras);
        JCodigoBarras.setBounds(30, 80, 680, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Código de Barras");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 50, 250, 20);

        JPrecoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        getContentPane().add(JPrecoVenda);
        JPrecoVenda.setBounds(210, 250, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Preco Compra");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 220, 110, 20);

        JPrecoCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        getContentPane().add(JPrecoCompra);
        JPrecoCompra.setBounds(30, 250, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // InsertBancoMySQL novoproduto = new InsertBancoMySQL();
        Model.Produtos produtos = new Produtos();

        DAO.Produtos.NovoProduto novoproduto = new DAO.Produtos.NovoProduto();

        boolean tudook = false;

        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        Date today = Calendar.getInstance().getTime();

        //TENTA PEGAR OS DADOS DO NOVO PRODUTO
        do {
            try {
                produtos.setCodigobarras(Integer.valueOf(JCodigoBarras.getText()));
                produtos.setNomeProduto(String.valueOf(JNomeProduto.getText()));
                produtos.setDescricao(String.valueOf(JDescricao.getText()));
                //VALOR TEM UM REPLACE CASO O USER INSIRA VIRGULA EM VEZ DE PONTO
                produtos.setPrecoVenda(Double.valueOf(JPrecoVenda.getText().replace(",", ".")));
                produtos.setPrecoCompra(Double.valueOf(JPrecoCompra.getText().replace(",", ".")));
                produtos.setQuantidade((Integer) jSpinnerQuantidadeProd.getValue());
                produtos.setDatacadastro(java.sql.Date.valueOf(LocalDate.MAX));

                tudook = true;

            } catch (NumberFormatException erro) {
                JOptionPane.showMessageDialog(null, "Verifique os dados inseridos");
                break;
            }
        } while (tudook == false);

        //SE O NOME DO PRODUTO FOR INVALIDO
        if (JNomeProduto.getText().length() <= 3) {
            JOptionPane.showMessageDialog(null, "Nome do produto muito curto");

            //SE O NOME DO FABRINCANTE FOR INVALIDO
        } else if (JDescricao.getText().length() <= 1) {

            JOptionPane.showMessageDialog(null, "Nome de Fabricante muito curto");

            //O ELSE GRAVA UM NOVO PRODUTO
        } else if (tudook == true) {

            novoproduto.InsertNovoProduto(produtos);

            JNomeProduto.setText("");
            JDescricao.setText("");
            JPrecoVenda.setText("");
            JPrecoCompra.setText("");
            jSpinnerQuantidadeProd.setValue(1);
            JCodigoBarras.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JCodigoBarras;
    private javax.swing.JTextField JDescricao;
    private javax.swing.JTextField JNomeProduto;
    private javax.swing.JFormattedTextField JPrecoCompra;
    private javax.swing.JFormattedTextField JPrecoVenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinnerQuantidadeProd;
    // End of variables declaration//GEN-END:variables
}
