package br.senac.sp.View;

import br.senac.sp.DAO.Produtos.Alterar;
import javax.swing.JOptionPane;
import javax.swing.text.View;


/**
 *
 * @author paulo.hbezerra
 */
public class MenuInicialTela extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MenuInicialTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JAlterarProduto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JCadastrarProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        JAlterarProduto.setText("Alterar Produto");
        JAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAlterarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(JAlterarProduto);
        JAlterarProduto.setBounds(120, 160, 170, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bereguetes Store");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 0, 310, 60);

        JCadastrarProduto.setText("Cadastrar Produtos");
        JCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCadastrarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(JCadastrarProduto);
        JCadastrarProduto.setBounds(120, 70, 170, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAlterarProdutoActionPerformed

        br.senac.sp.View.AlterarProdutoTela alterarproduto = new AlterarProdutoTela();

        alterarproduto.setSize(800, 800);
        alterarproduto.setVisible(true);
        alterarproduto.setResizable(false);
        alterarproduto.setLocationRelativeTo(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_JAlterarProdutoActionPerformed

    private void JCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCadastrarProdutoActionPerformed

        br.senac.sp.View.NovoProdutoTela novoproduto = new NovoProdutoTela();
        novoproduto.setSize(800, 800);
        novoproduto.setVisible(true);
        novoproduto.setResizable(false);
        novoproduto.setLocationRelativeTo(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_JCadastrarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                br.senac.sp.View.MenuInicialTela telaInicial = new MenuInicialTela();
                telaInicial.setSize(400, 400);
                telaInicial.setVisible(true);
                telaInicial.setResizable(false);
                telaInicial.setLocationRelativeTo(null);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAlterarProduto;
    private javax.swing.JButton JCadastrarProduto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
